/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

import Common.Validations;
import java.util.List;
import javax.swing.JOptionPane;
import modelDAO.BookStockDAO;
import modelDAO.BooksDAO;
import modelTO.BookStockTO;
import modelTO.BooksTO;

/**
 *
 * @author Shobhit
 */
public class BookStockDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form BookStockDetails
     */
    public BookStockDetails() {
        initComponents();
        bindBookNames();
        bindBookId();

    }

    private void bindBookNames() {
        List<BooksTO> books = new BooksDAO().getAllRecord();
        jBookName.removeAllItems();
        jBookName.addItem("--Select Book Name--");
        for (BooksTO record : books) {
            jBookName.addItem(record.getBookName());
        }
    }

    private void bindBookId() {
        List<BooksTO> books = new BooksDAO().getAllRecord();
        jBookId.removeAllItems();
        jBookId.addItem("--Select Book Id--");
        for (BooksTO record : books) {
            jBookId.addItem(String.valueOf(record.getBookId()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jtfQuantity = new javax.swing.JTextField();
        jrbIN = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jrbOut = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jBookId = new javax.swing.JComboBox<>();
        jBookName = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("STOCK MODIFIER");

        buttonGroup1.add(jrbIN);
        jrbIN.setText("IN");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("BOOK NAME :");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("QUANTITY :");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("BOOK ID :");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("STOCK TYPE :");

        buttonGroup1.add(jrbOut);
        jrbOut.setText("OUT");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("UPDATE STOCK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBookId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jBookId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jBookIdItemStateChanged(evt);
            }
        });

        jBookName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jBookName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jBookNameItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jBookName, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBookId, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jrbIN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                        .addComponent(jrbOut))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbOut)
                    .addComponent(jrbIN))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jtfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean state1, state2;
    private void jBookNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jBookNameItemStateChanged
        if (!state2) {
            if (jBookName.getSelectedIndex() > 0) {
                state1 = true;
                jBookId.setSelectedIndex(jBookName.getSelectedIndex());
                state1 = false;
            }
        }
    }//GEN-LAST:event_jBookNameItemStateChanged

    private void jBookIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jBookIdItemStateChanged
        if (!state1) {
            if (jBookId.getSelectedIndex() > 0) {
                state2 = true;
                jBookName.setSelectedIndex(jBookId.getSelectedIndex());
                state2 = false;
            }
        }

    }//GEN-LAST:event_jBookIdItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean allValid = true;
        String message = "";
        BooksDAO bdao = new BooksDAO();
        BookStockDAO dao = new BookStockDAO();

        if (jBookId.getSelectedIndex() == 0) {
            allValid = false;
            message += "Please Select Book Id";
        } else if (jBookName.getSelectedIndex() == 0) {
            allValid = false;
            message += "Please Select Book Id";
        }

        String entryType = "";
        if (jrbIN.isSelected()) {
            entryType = jrbIN.getText();
        } else if (jrbOut.isSelected()) {
            entryType = jrbOut.getText();
        }

        if (entryType.isEmpty()) {
            allValid = false;
            message += "Please select Entry type";
        }
        String quantity = jtfQuantity.getText();
        if (quantity.isEmpty()) {
            allValid = false;
            message += "Enter some quantity";
        } else if (Validations.isNumber(quantity)) {
            int qty = Integer.parseInt(quantity);
            if (qty <= 0) {
                message += "Please Enter Positive Number in Quantity Box\n\n";
                allValid = false;
            }
        } else {
            message += "Please Enter Number in Quantity\n\n";
            allValid = false;
        }

        if (allValid) {
            BookStockTO record = new BookStockTO();
            record.setBookId(Integer.parseInt(jBookId.getSelectedItem().toString()));
            record.setEntryType(entryType);
            record.setQuantity(Integer.parseInt(quantity));
            BooksTO bookRec = new BooksDAO().getBook(record.getBookId());
            if (entryType.equals("IN")) {
                bookRec.setQuantity(bookRec.getQuantity() + record.getQuantity());
                if (dao.insertRecord(record) && bdao.updateRecord(bookRec)) {
                    message = "entry is updated";
                } else {
                    message = "Entry is not updated";
                }
            } else if (entryType.equals("OUT")) {
                if (bookRec.getQuantity() >= record.getQuantity()) {
                    bookRec.setQuantity(bookRec.getQuantity() - record.getQuantity());
                    if (dao.insertRecord(record) && bdao.updateRecord(bookRec)) {
                        message = "entry is updated";
                    } else {
                        message = "Entry is not updated";
                    }
                } else {
                    message = "There is no Enough Quantity Present";
                }
            } else {
                message = "Invalid Stock Type";
            }
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jBookId;
    private javax.swing.JComboBox<String> jBookName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jrbIN;
    private javax.swing.JRadioButton jrbOut;
    private javax.swing.JTextField jtfQuantity;
    // End of variables declaration//GEN-END:variables
}
