/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

import Common.CommonOperation;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import modelDAO.BookTypeDAO;
import modelTO.BookTypeTO;
import modelTO.BooksTO;

/**
 *
 * @author Shobhit
 */
public class LibraryManagement extends javax.swing.JFrame {

    /**
     * Creates new form LibraryManagement
     */
    public LibraryManagement() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        addBook = new javax.swing.JMenuItem();
        viewBooks = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        typeViewer = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmAddMember = new javax.swing.JMenuItem();
        jmViewMember = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jIssueMenu = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        jLabel1.setText("TODAY  A  READER,  TOMORROW  A  LEADER");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/library-100616524-large.jpg"))); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu3.setText("Books");

        addBook.setText("Add new Book");
        addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookActionPerformed(evt);
            }
        });
        jMenu3.add(addBook);

        viewBooks.setText("View All Books");
        viewBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBooksActionPerformed(evt);
            }
        });
        jMenu3.add(viewBooks);

        jMenuItem1.setText("Add Book Type");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        typeViewer.setText("View Book Types");
        typeViewer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeViewerActionPerformed(evt);
            }
        });
        jMenu3.add(typeViewer);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Members");

        jmAddMember.setText("Add Member");
        jmAddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAddMemberActionPerformed(evt);
            }
        });
        jMenu1.add(jmAddMember);

        jmViewMember.setText("View Members");
        jmViewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmViewMemberActionPerformed(evt);
            }
        });
        jMenu1.add(jmViewMember);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Stock Operation");

        jMenuItem2.setText("Stock Entry");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        jIssueMenu.setText("Issue/Return");

        jMenuItem4.setText("Issue");
        jIssueMenu.add(jMenuItem4);

        jMenuItem3.setText("Return");
        jIssueMenu.add(jMenuItem3);

        jMenuBar1.add(jIssueMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookActionPerformed
        List<BookTypeTO> rec;
        BookTypeDAO dao = new BookTypeDAO();
        rec = dao.getAllRecord();
        if (rec != null && rec.size() > 0) {
            CommonOperation.openInternalFrame(jDesktopPane1, new BookAdder());
        }
        else{
            JOptionPane.showMessageDialog(this, "No book types exist enter book types first");
        }
    }//GEN-LAST:event_addBookActionPerformed

    private void viewBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBooksActionPerformed
        CommonOperation.openInternalFrame(jDesktopPane1, new BookViewer());
    }//GEN-LAST:event_viewBooksActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CommonOperation.openInternalFrame(jDesktopPane1, new AddBookType());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void typeViewerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeViewerActionPerformed
        CommonOperation.openInternalFrame(jDesktopPane1, new ViewBookType());
    }//GEN-LAST:event_typeViewerActionPerformed

    private void jmAddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAddMemberActionPerformed
        CommonOperation.openInternalFrame(jDesktopPane1, new AddMember());
    }//GEN-LAST:event_jmAddMemberActionPerformed

    private void jmViewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmViewMemberActionPerformed
        CommonOperation.openInternalFrame(jDesktopPane1, new ViewMembers());
    }//GEN-LAST:event_jmViewMemberActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CommonOperation.openInternalFrame(jDesktopPane1, new BookStockDetails());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addBook;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jIssueMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jmAddMember;
    private javax.swing.JMenuItem jmViewMember;
    private javax.swing.JMenuItem typeViewer;
    private javax.swing.JMenuItem viewBooks;
    // End of variables declaration//GEN-END:variables
}
